###
GET https://moises-api.vercel.app HTTP/1.1



### LOGIN
POST  https://moises-api.vercel.app/auth/login HTTP/1.1
Content-Type: application/json

{
    "email":"admin@correo.com",
    "password":"admin"
}



### GET USERS
GET https://moises-api.vercel.app/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YWE1YzVjZTk3YmUzZmEwNTYxMDgxMyIsImVtYWlsIjoiYWRtaW5AY29ycmVvLmNvbSIsInVzZXJuYW1lIjoiYWRtaW4iLCJpYXQiOjE3Mzk2NTQyODMsImV4cCI6MTczOTY1Nzg4M30.VJwvZQVNa0mUMWRDoxjXnZzO0ZDOR3Q-ymkSsjp5Bbs



### GET INVOICES
GET https://moises-api.vercel.app/invoices HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YWE1YzVjZTk3YmUzZmEwNTYxMDgxMyIsImVtYWlsIjoiYWRtaW5AY29ycmVvLmNvbSIsInVzZXJuYW1lIjoiYWRtaW4iLCJpYXQiOjE3Mzk2NTQyODMsImV4cCI6MTczOTY1Nzg4M30.VJwvZQVNa0mUMWRDoxjXnZzO0ZDOR3Q-ymkSsjp5Bbs

### GET INVOICES COUNT
GET https://moises-api.vercel.app/invoices/count HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YWE1YzVjZTk3YmUzZmEwNTYxMDgxMyIsImVtYWlsIjoiYWRtaW5AY29ycmVvLmNvbSIsInVzZXJuYW1lIjoiYWRtaW4iLCJpYXQiOjE3Mzk2NTQyODMsImV4cCI6MTczOTY1Nzg4M30.VJwvZQVNa0mUMWRDoxjXnZzO0ZDOR3Q-ymkSsjp5Bbs

### GET INVOICES STATUS
GET https://moises-api.vercel.app/invoices/status-count HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YWE1YzVjZTk3YmUzZmEwNTYxMDgxMyIsImVtYWlsIjoiYWRtaW5AY29ycmVvLmNvbSIsInVzZXJuYW1lIjoiYWRtaW4iLCJpYXQiOjE3Mzk2NTQyODMsImV4cCI6MTczOTY1Nzg4M30.VJwvZQVNa0mUMWRDoxjXnZzO0ZDOR3Q-ymkSsjp5Bbs

### GET CUSTOMERS
GET https://moises-api.vercel.app/customer HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YWE1YzVjZTk3YmUzZmEwNTYxMDgxMyIsImVtYWlsIjoiYWRtaW5AY29ycmVvLmNvbSIsInVzZXJuYW1lIjoiYWRtaW4iLCJpYXQiOjE3Mzk2NTQyODMsImV4cCI6MTczOTY1Nzg4M30.VJwvZQVNa0mUMWRDoxjXnZzO0ZDOR3Q-ymkSsjp5Bbs




### CREATE INVOICE
POST   https://moises-api.vercel.app/invoices HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YWE1YzVjZTk3YmUzZmEwNTYxMDgxMyIsImVtYWlsIjoiYWRtaW5AY29ycmVvLmNvbSIsInVzZXJuYW1lIjoiYWRtaW4iLCJpYXQiOjE3Mzk2NTQyODMsImV4cCI6MTczOTY1Nzg4M30.VJwvZQVNa0mUMWRDoxjXnZzO0ZDOR3Q-ymkSsjp5Bbs

{
    "amount":10000,
    "status":"pending",
    "date":"2025-03-20",
    "customer":"67aa5da9e97be3fa0561081d"
}

### GET REVENUES
GET https://moises-api.vercel.app/revenues HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YWE1YzVjZTk3YmUzZmEwNTYxMDgxMyIsImVtYWlsIjoiYWRtaW5AY29ycmVvLmNvbSIsInVzZXJuYW1lIjoiYWRtaW4iLCJpYXQiOjE3Mzk2NTQyODMsImV4cCI6MTczOTY1Nzg4M30.VJwvZQVNa0mUMWRDoxjXnZzO0ZDOR3Q-ymkSsjp5Bbs



